name: Tretton37CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/tretton37
            rm -rf node_modules yarn.lock
            git switch master
            git reset --hard origin/master
            git pull
            yarn
            cd /var/www/html
            pm2 stop tretton37
            pm2 delete tretton37
            pm2 flush
            pm2 start ecosystem.config.js --env production
            pm2 save
            pm2 log tretton37 --nostream 
